# Generated content
[tasks.generate-icons]
cwd = "scripts"
script = """
npm run --silent vscode_material_icons > "../src/generated/vscode_material_icons.rs"
npm run --silent material_icons > "../src/generated/material_icons.rs"
"""

# Build
[tasks.pre-build-wasm]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.opt-wasm]
dependencies = ["pre-build-wasm"]
command = "wasm-opt"
cwd = "target/wasm32-unknown-unknown/release"
args = ["-O3", "-all", "-o", "reqtk_opt.wasm", "reqtk.wasm"]

[tasks.bindgen-wasm]
dependencies = ["opt-wasm"]
cwd = "target/wasm32-unknown-unknown/release"
command = "wasm-bindgen"
args = ["--out-dir", ".", "--target", "web", "reqtk_opt.wasm"]

[tasks.build-wasm]
dependencies = ["bindgen-wasm"]
cwd = "target/wasm32-unknown-unknown/release"
command = "ls"
args = ["-lh", "./reqtk.wasm", "./reqtk_opt.wasm", "./reqtk_opt_bg.wasm"]

# Requirements
[tasks.requirements]
command = "cargo"
args = ["run", "--", "convert", "requirements.req", "-o", "REQUIREMENTS.md"]
